version: "3"

services:
    app:
        build:
            context: . # path to the Dockerfile
        ports:
            - "8000:8000"
        volumes: # make updates in the project into Docker image in real time, restart Docker is not required
            # automatically update it when changes detected locally
            - ./app:/app
        command: > # > to break the line # run application in the Docker container: run with docker-compose up
            sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=superpassword
        depends_on: 
            - db # run the db first and connect the db host in the app service

    db:
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=superpassword